services:
  baikalctl:
    image: rstms/baikalctl:${BAIKALCTL_VERSION:-latest}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./certs:/home/baikalctl/certs
    environment:
      BAIKALCTL_USERNAME:
      BAIKALCTL_PASSWORD:
      BAIKALCTL_URL:
      BAIKALCTL_ADDRESS:
      BAIKALCTL_PORT:
      BAIKALCTL_CERT:
      BAIKALCTL_KEY:
      BAIKALCTL_LOG_LEVEL:
      BAIKALCTL_DEBUG:
      BAIKALCTL_VERBOSE:
      BAIKALCTL_PROFILE:
      BAIKALCTL_XVNC_VERBOSE:
      BAIKALCTL_PROFILE_CREATE_TIMEOUT:
