#!/bin/bash
set -ue 

cmd=
if [ $# > 0 ]; then
    cmd=$1
fi

if [ $cmd = 'server' ]; then
    export DISPLAY=:1
    vncserver :1 >vncserver.log 2>&1 &
    baikalctl server
    pkill vncserver
else
    baikalctl "$@"
fi
