#!/bin/sh

set -ue 

cmd=
if [ $# -gt 0 ]; then
    cmd=$1
fi

if [ -n "${BAIKAL_SHOW_CONFIG:-}" ]; then
    baikalctl --show-config
fi

if [ $cmd = 'server' ]; then
    export DISPLAY=:1
    if [ -n "${BAIKAL_SHOW_VNCSERVER_LOG:-}" ]; then
	vncserver :1 &
    else
	vncserver :1 >/dev/null 2>&1 &
    fi
    baikalctl server
    pkill vncserver
else
    baikalctl --api http://localhost:8000 "$@"
fi
